### ISSUE TITLE
Update to Vite 5

### ISSUE THREAD

**Issue by ai** [TheSeally/vite-plugin-pug-transformer#11]
Now we have warnings:

```
plugin 'vite-plugin-pug-transformer' uses deprecated 'enforce' option. Use 'order' option instead.
plugin 'vite-plugin-pug-transformer' uses deprecated 'transform' option. Use 'handler' option instead.
```

**Comment by TheSeally** [comment]
Hi, thanks for issue.

I fixed this warnings in [this commit](https://github.com/TheSeally/vite-plugin-pug-transformer/commit/a0f24510bd9c6bc9c2966274d991a97ef69a23ab) and release new version
