### ISSUE TITLE
pretty : true

### ISSUE THREAD

**Issue by csskiller** [TheSeally/vite-plugin-pug-transformer#12]
Hi! 

great plugin :) thanks

Is there a way to not unminify the html? pretty is deprecated, and i cant find another way to not minify the code 🙏 

Thanks!

**Comment by TheSeally** [comment]
Hi

Unfortunately, there is no way how to unminify html without `pretty`. I haven't found other options to tell pug not to minify code
And as I understand, author of pug [don't like the idea](https://github.com/pugjs/pug/issues/3291#issuecomment-724709352) of pretty printing HTML

I think that you have two options:
- still use `pretty`. We don't know when new major version of pug is coming. So maybe it is not a problem using deprecated property for your project
- use other pretty printing tools like prettier
